### ISSUE TITLE
Nameserver service

### ISSUE THREAD

**Issue by rithvikvibhu** [namebasehq/awesome-handshake#11]
Cloudflare and other nameserver hosts don't support Handshake. They verify the domain with ICANN (and the list of TLDs).

Are there any (free) services that work with Handshake domains?

---

Services that support handshake:
- [AWS Route53](https://aws.amazon.com/route53/) - Works
- [ServerSpace](https://serverspace.io/services/dns-hosting/) - Works, but zones may be deleted in 2 weeks; contacted support
- [NS1](https://ns1.com/) - Possible, requires credit card even on free plan

Services do **NOT** support handshake:
- [Cloudflare](https://cloudflare.com)
- [CouDNS](https://www.cloudns.net)
- [FreeDNS](https://freedns.afraid.org)
- [Hurricane Electric](https://dns.he.net)
- [NameCheap](https://www.namecheap.com/domains/freedns)

**Comment by turbomaze** [comment]
Depending on your use case this may or may not be helpful to you, but if the name is attached to a Namebase account then we provide free nameserver services for you.

If the name you'd like to use is not associated with a namebase account, I'm not currently aware of free hosted nameservers that will "just work". I've chatted with some small hosting websites before that expressed interest in making the (small) modifications necessary to support Handshake, but never followed through to completion.

Other options:

1) Run your own nameserver (something like PowerDNS could be good) on a $5/mo digital ocean droplet
2) Run the nameserver *with* your webserver! Depending on what kind of DNS records you want to set you might be able to get away with running nameserver software on the same machine that you're running your website. Check out this cool project for a library that does this for you easily: https://github.com/pinheadmz/handout

I hope this helps, if not, I'd like to hear about what you're experimenting with to better understand your nameserver needs

**Comment by rithvikvibhu** [comment]
I'll be moving the names to Namebase as soon as they add Name Withdrawal (which I believe is already in the works).

Running a nameserver (while it does sound like fun) is a bit much to host static sites. Handout is interesting, but the problem is that I deploy apps to PaaS like heroku/azure so won't have access to run a custom server.

>I've chatted with some small hosting websites before that expressed interest

I really do hope Handshake picks up :crossed_fingers:

**Comment by rithvikvibhu** [comment]
I'm not sure, but while trying different services, came across https://serverspace.io and could add my handshake name! Well, they only allow SLD and third level, but it's still something.

I don't have any free name right now to test so if someone could verify that it works, would be great. And if it works, can add it to the awesome list.

**Comment by turbomaze** [comment]
@rithvikvibhu That's an interesting find! I've just gifted the email address in your Github profile a Handshake name so you can test it out. If you'd prefer to receive the name at a different email address let me know.

BTW name withdrawals are imminent. There was a small Handshake wallet bug that was blocking this that got fixed a little over a month ago, and we're in the middle of wrapping up the UI to get name withdrawals live for all our users. In the meantime we have been processing name withdrawal requests manually for users.

**Comment by rithvikvibhu** [comment]
Thanks for the name @turbomaze! I didn't have any HNS on Namebase (to update dns), so transferred some and now waiting for the 6 confirmations. I'll test it in an hour or so.

>BTW name withdrawals are imminent.

That's good to know. I'll be moving then. :p

**Comment by turbomaze** [comment]
Ah oops, forgot about network fees. I've gifted your account some HNS as well

**Comment by rithvikvibhu** [comment]
So an update (no, I didn't run away with the name and HNS :p).

Turns out that updating DNS records on the blockchain takes a lot of time to propagate (>6 hours) and to get through all the caches. This makes using an external nameserver all the more essential.

I first set it to ServerSpace's nameservers, and waited for Namebase to sync (which took ~an hour). Turned out, I set it at the root level (giftsld.), not at second level which ServerSpace expects (test.giftsld.)

By the time I set it again at test.giftsld, it was already ~4 hours and it still wasn't working, so decided to try another service. Picked Amazon's Route53 and set it up this way (below).

To find out when the records are really updated and available, I also added a TXT record and waited till it showed up (otherwise, was in the blind).

**Now that it's confirmed that Route53 works, gonna go back to ServerSpace and try again. Will leave it overnight and test it in ~10 hours.** (btw I've already replaced the records, so you might not be able to look this up now)
**Edit:** This works too. Updated the first comment with the complete list.

Route53 hosted zone:
![image](https://user-images.githubusercontent.com/5113343/98971647-73227880-2537-11eb-8744-fad6b4dc224a.png)

Custom nameserver in Namebase:
![image](https://user-images.githubusercontent.com/5113343/98973073-47a08d80-2539-11eb-80cd-095d52ae1996.png)

Querying DNS records from Route53 (after a really long wait):
![image](https://user-images.githubusercontent.com/5113343/98972855-060fe280-2539-11eb-91ed-5ec50fb31298.png)

**Comment by rithvikvibhu** [comment]
Also, I had contacted NS1 and got a promising reply:
>Hi,
>
>Thank you for contacting NS1 Support.
>
>We allow all kinds of names to be added as zones to our systems without much restriction apart from that it must pass a regex test as being in a valid domain name format. We have tested 'welcome.nb' and it created successfully, so this should be fine for your purposes.
>
>Regards,

They have a free plan, and I'm gonna test that out soon.

**Comment by turbomaze** [comment]
Amazing updates, really glad you're looking into all this

**Comment by balupton** [comment]
For reference, there is the following feature request for support within AdGuard Home:

https://github.com/AdguardTeam/AdGuardHome/issues/1609

**Comment by rithvikvibhu** [comment]
> For reference, there is the following feature request for support within AdGuard Home:
> 
> [AdguardTeam/AdGuardHome#1609](https://github.com/AdguardTeam/AdGuardHome/issues/1609)

That sounds exciting! Having AdGuard also resolve handshake names would be nice.
This issue however is for hosting handshake nameservers off-chain; More for people who own handshake names, rather than users.

**Comment by Nathanwoodburn** [comment]
G'day,
I've added some resolvers I know work. Can you provide some more that still work?

**Comment by rithvikvibhu** [comment]
This is an old issue and there are better DNSSEC-enabled DNS hosts like Varo now, which have already been added. Closing.
